micronaut:
  application:
    name: micronaut-example-mvn
  
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/mbrs?ssl=false
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
 
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true